kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: "/home/ujjwal/ATU/0. assignments/rag-mlops-system/runtime-artifacts"
        containerPath: /runtime-artifacts

      - hostPath: "/home/ujjwal/ATU/0. assignments/rag-mlops-system/models/sentence-transformers"
        containerPath: /models/sentence-transformers
