apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: rag-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      enableServiceLinks: false
      containers:
        - name: rag-api
          image: ghcr.io/rastogiujj12/rag-mlops:18f7d37573937b017e4732bba612678f3c6f2b55
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: RAG_LLM_PROVIDER
              value: "stub"
            - name: RAG_EMBEDDING_CACHE_DIR
              value: "/models/sentence-transformers"
            - name: RAG_EMBEDDING_OFFLINE
              value: "false"
          volumeMounts:
            - name: outputs
              mountPath: /app/outputs
            - name: artifacts
              mountPath: /app/artifacts
            - name: processed-data
              mountPath: /app/data/processed
            - name: embedding-cache
              mountPath: /models/sentence-transformers
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: outputs
          hostPath:
            path: /runtime-artifacts/outputs
            type: Directory

        - name: artifacts
          hostPath:
            path: /runtime-artifacts/artifacts
            type: DirectoryOrCreate

        - name: processed-data
          hostPath:
            path: /runtime-artifacts/data/processed
            type: Directory

        - name: embedding-cache
          hostPath:
            path: /models/sentence-transformers
            type: DirectoryOrCreate
